import type { FormTemplate } from "@/lib/forms/types";

/**
 * Phase 4 — Operational & Compliance Form Templates
 * Covers: Supervision, Physical Intervention, Body Map, Education (PEP),
 * CiC Review Prep, Reg 44 Visit, Transition Planning, Complaints,
 * Night Check, and De-escalation Plan.
 */

export const PHASE4_TEMPLATES: Record<string, FormTemplate> = {

  // ── 1. Staff Supervision Record ─────────────────────────────────────────────
  supervision_record: {
    id: "tpl-supervision-record",
    code: "supervision_record",
    name: "Staff Supervision Record",
    category: "Staff & HR",
    status: "approved",
    description: "Formal 1:1 supervision session record for residential care staff",
    latest_version: {
      id: "v-supervision-record-1",
      template_id: "tpl-supervision-record",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-sup-details",
            title: "Supervision Details",
            section_order: 1,
            fields: [
              {
                id: "f-sup-date",
                field_key: "supervision_date",
                field_type: "date",
                label: "Date of Supervision",
                required: true,
                field_order: 1,
                section_id: "sec-sup-details",
              },
              {
                id: "f-sup-staff",
                field_key: "staff_member",
                field_type: "staff_selector",
                label: "Staff Member Being Supervised",
                required: true,
                field_order: 2,
                section_id: "sec-sup-details",
              },
              {
                id: "f-sup-supervisor",
                field_key: "supervisor",
                field_type: "staff_selector",
                label: "Supervisor",
                required: true,
                field_order: 3,
                section_id: "sec-sup-details",
              },
              {
                id: "f-sup-type",
                field_key: "supervision_type",
                field_type: "single_select",
                label: "Type of Supervision",
                required: true,
                options: [
                  { label: "Planned 1:1", value: "planned" },
                  { label: "Probationary Review", value: "probationary" },
                  { label: "Post-Incident", value: "post_incident" },
                  { label: "Return to Work", value: "return_to_work" },
                  { label: "Informal", value: "informal" },
                ],
                field_order: 4,
                section_id: "sec-sup-details",
              },
              {
                id: "f-sup-duration",
                field_key: "duration_minutes",
                field_type: "number",
                label: "Duration (minutes)",
                required: true,
                field_order: 5,
                section_id: "sec-sup-details",
              },
            ],
          },
          {
            id: "sec-sup-wellbeing",
            title: "Wellbeing & Workload",
            section_order: 2,
            fields: [
              {
                id: "f-sup-wellbeing-rating",
                field_key: "wellbeing_rating",
                field_type: "risk_rating",
                label: "How is the staff member's wellbeing? (1 = struggling, 5 = thriving)",
                required: true,
                field_order: 1,
                section_id: "sec-sup-wellbeing",
              },
              {
                id: "f-sup-workload",
                field_key: "workload_comments",
                field_type: "long_text",
                label: "Workload and capacity — any concerns?",
                required: false,
                field_order: 2,
                section_id: "sec-sup-wellbeing",
              },
              {
                id: "f-sup-concerns",
                field_key: "concerns_raised",
                field_type: "yes_no",
                label: "Did the staff member raise any concerns?",
                required: true,
                field_order: 3,
                section_id: "sec-sup-wellbeing",
              },
              {
                id: "f-sup-concern-detail",
                field_key: "concern_detail",
                field_type: "long_text",
                label: "Detail of concerns raised",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "concerns_raised", operator: "equals", value: true },
                  },
                ],
                field_order: 4,
                section_id: "sec-sup-wellbeing",
              },
            ],
          },
          {
            id: "sec-sup-practice",
            title: "Practice & Development",
            section_order: 3,
            fields: [
              {
                id: "f-sup-practice-discussion",
                field_key: "practice_discussion",
                field_type: "ai_assisted_narrative",
                label: "Discussion of practice — cases, approaches, reflections",
                help_text: "Summarise what was discussed regarding the staff member's direct work with young people.",
                required: true,
                field_order: 1,
                section_id: "sec-sup-practice",
              },
              {
                id: "f-sup-strengths",
                field_key: "strengths_identified",
                field_type: "long_text",
                label: "Strengths identified",
                required: false,
                field_order: 2,
                section_id: "sec-sup-practice",
              },
              {
                id: "f-sup-development",
                field_key: "development_areas",
                field_type: "long_text",
                label: "Development areas / learning needs",
                required: false,
                field_order: 3,
                section_id: "sec-sup-practice",
              },
              {
                id: "f-sup-training",
                field_key: "training_identified",
                field_type: "short_text",
                label: "Any training needs identified",
                required: false,
                field_order: 4,
                section_id: "sec-sup-practice",
              },
            ],
          },
          {
            id: "sec-sup-actions",
            title: "Actions & Next Supervision",
            section_order: 4,
            fields: [
              {
                id: "f-sup-actions",
                field_key: "agreed_actions",
                field_type: "long_text",
                label: "Agreed actions (with owner and timescale)",
                required: false,
                field_order: 1,
                section_id: "sec-sup-actions",
              },
              {
                id: "f-sup-next-date",
                field_key: "next_supervision_date",
                field_type: "date",
                label: "Date of next supervision",
                required: false,
                field_order: 2,
                section_id: "sec-sup-actions",
              },
              {
                id: "f-sup-staff-signature",
                field_key: "staff_signature",
                field_type: "signature",
                label: "Staff member signature",
                required: true,
                field_order: 3,
                section_id: "sec-sup-actions",
              },
              {
                id: "f-sup-supervisor-signature",
                field_key: "supervisor_signature",
                field_type: "signature",
                label: "Supervisor signature",
                required: true,
                field_order: 4,
                section_id: "sec-sup-actions",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 2. Physical Intervention Record ─────────────────────────────────────────
  physical_intervention_record: {
    id: "tpl-physical-intervention",
    code: "physical_intervention_record",
    name: "Physical Intervention Record",
    category: "Incident / Safeguarding",
    status: "approved",
    description: "Record of a physical intervention (restraint) — required by Ofsted",
    latest_version: {
      id: "v-physical-intervention-1",
      template_id: "tpl-physical-intervention",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-pi-child",
            title: "Child & Incident Details",
            section_order: 1,
            fields: [
              {
                id: "f-pi-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-pi-child",
              },
              {
                id: "f-pi-date",
                field_key: "incident_datetime",
                field_type: "datetime",
                label: "Date & Time of Intervention",
                required: true,
                field_order: 2,
                section_id: "sec-pi-child",
              },
              {
                id: "f-pi-location",
                field_key: "location",
                field_type: "short_text",
                label: "Location within the home",
                required: true,
                field_order: 3,
                section_id: "sec-pi-child",
              },
              {
                id: "f-pi-staff-involved",
                field_key: "staff_involved",
                field_type: "multi_select",
                label: "Staff involved in the intervention",
                required: true,
                field_order: 4,
                section_id: "sec-pi-child",
              },
              {
                id: "f-pi-witnesses",
                field_key: "witnesses",
                field_type: "short_text",
                label: "Any other witnesses (names)",
                required: false,
                field_order: 5,
                section_id: "sec-pi-child",
              },
            ],
          },
          {
            id: "sec-pi-context",
            title: "Context & De-escalation Attempts",
            section_order: 2,
            fields: [
              {
                id: "f-pi-antecedents",
                field_key: "antecedents",
                field_type: "ai_assisted_narrative",
                label: "What led to the intervention? (Antecedents)",
                help_text: "Describe events or triggers that preceded the need for intervention.",
                required: true,
                field_order: 1,
                section_id: "sec-pi-context",
              },
              {
                id: "f-pi-deescalation",
                field_key: "deescalation_attempts",
                field_type: "multi_select",
                label: "De-escalation strategies attempted before intervention",
                required: true,
                options: [
                  { label: "Verbal de-escalation", value: "verbal" },
                  { label: "Space/withdrawal", value: "withdrawal" },
                  { label: "Distraction", value: "distraction" },
                  { label: "Redirection", value: "redirection" },
                  { label: "Sensory support", value: "sensory" },
                  { label: "Called for support", value: "called_support" },
                  { label: "Other", value: "other" },
                ],
                field_order: 2,
                section_id: "sec-pi-context",
              },
              {
                id: "f-pi-deesc-detail",
                field_key: "deescalation_detail",
                field_type: "long_text",
                label: "Detail of de-escalation attempts",
                required: true,
                field_order: 3,
                section_id: "sec-pi-context",
              },
              {
                id: "f-pi-risk",
                field_key: "risk_justification",
                field_type: "long_text",
                label: "What risk necessitated the intervention?",
                help_text: "Describe the immediate risk to the young person or others that justified the use of physical intervention.",
                required: true,
                field_order: 4,
                section_id: "sec-pi-context",
              },
            ],
          },
          {
            id: "sec-pi-technique",
            title: "Intervention Detail",
            section_order: 3,
            fields: [
              {
                id: "f-pi-technique",
                field_key: "technique_used",
                field_type: "single_select",
                label: "Type of intervention used",
                required: true,
                options: [
                  { label: "Guiding hold", value: "guiding_hold" },
                  { label: "Supportive hold", value: "supportive_hold" },
                  { label: "Seated position", value: "seated" },
                  { label: "Standing position", value: "standing" },
                  { label: "Supine position (floor)", value: "supine" },
                  { label: "Other approved technique", value: "other" },
                ],
                field_order: 1,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-duration",
                field_key: "duration_minutes",
                field_type: "number",
                label: "Duration of intervention (minutes)",
                required: true,
                field_order: 2,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-narrative",
                field_key: "intervention_narrative",
                field_type: "ai_assisted_narrative",
                label: "Factual account of the intervention",
                help_text: "Provide a clear, objective, chronological account of what happened during the intervention.",
                required: true,
                field_order: 3,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-injury-yp",
                field_key: "injury_to_child",
                field_type: "yes_no",
                label: "Did the young person sustain any injury?",
                required: true,
                field_order: 4,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-injury-yp-detail",
                field_key: "child_injury_detail",
                field_type: "long_text",
                label: "Describe the injury and first aid provided",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "injury_to_child", operator: "equals", value: true },
                  },
                ],
                field_order: 5,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-injury-staff",
                field_key: "injury_to_staff",
                field_type: "yes_no",
                label: "Did any staff member sustain any injury?",
                required: true,
                field_order: 6,
                section_id: "sec-pi-technique",
              },
              {
                id: "f-pi-injury-staff-detail",
                field_key: "staff_injury_detail",
                field_type: "long_text",
                label: "Describe staff injury and first aid provided",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "injury_to_staff", operator: "equals", value: true },
                  },
                ],
                field_order: 7,
                section_id: "sec-pi-technique",
              },
            ],
          },
          {
            id: "sec-pi-after",
            title: "After Care & Notifications",
            section_order: 4,
            fields: [
              {
                id: "f-pi-aftercare",
                field_key: "aftercare_provided",
                field_type: "long_text",
                label: "What support did you provide to the young person after the intervention?",
                required: true,
                field_order: 1,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-yp-response",
                field_key: "young_person_response",
                field_type: "long_text",
                label: "How did the young person respond during and after the intervention?",
                required: true,
                field_order: 2,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-manager-notified",
                field_key: "manager_notified",
                field_type: "yes_no",
                label: "Was the on-call manager notified?",
                required: true,
                field_order: 3,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-la-notified",
                field_key: "la_notified",
                field_type: "yes_no",
                label: "Was the local authority (placing authority) notified?",
                required: true,
                field_order: 4,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-la-notified-by",
                field_key: "la_notified_by",
                field_type: "short_text",
                label: "Who at the LA was notified and when?",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "la_notified", operator: "equals", value: true },
                  },
                ],
                field_order: 5,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-body-map-attached",
                field_key: "body_map_attached",
                field_type: "yes_no",
                label: "Is a body map attached to this record?",
                required: true,
                field_order: 6,
                section_id: "sec-pi-after",
              },
              {
                id: "f-pi-learning",
                field_key: "learning_points",
                field_type: "long_text",
                label: "What learning has come from this incident?",
                required: false,
                field_order: 7,
                section_id: "sec-pi-after",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 3. Body Map / Injury Documentation ──────────────────────────────────────
  body_map_injury: {
    id: "tpl-body-map",
    code: "body_map_injury",
    name: "Body Map — Injury / Mark Documentation",
    category: "Incident / Safeguarding",
    status: "approved",
    description: "Record of marks, injuries or bruising observed on a young person",
    latest_version: {
      id: "v-body-map-1",
      template_id: "tpl-body-map",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-bm-details",
            title: "Observation Details",
            section_order: 1,
            fields: [
              {
                id: "f-bm-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-bm-details",
              },
              {
                id: "f-bm-date",
                field_key: "observed_datetime",
                field_type: "datetime",
                label: "Date & Time Observed",
                required: true,
                field_order: 2,
                section_id: "sec-bm-details",
              },
              {
                id: "f-bm-staff",
                field_key: "recorded_by",
                field_type: "staff_selector",
                label: "Recorded By",
                required: true,
                field_order: 3,
                section_id: "sec-bm-details",
              },
              {
                id: "f-bm-context",
                field_key: "observation_context",
                field_type: "single_select",
                label: "When was this observed?",
                required: true,
                options: [
                  { label: "Personal care / washing", value: "personal_care" },
                  { label: "Morning routine", value: "morning_routine" },
                  { label: "During activities", value: "activities" },
                  { label: "After an incident", value: "post_incident" },
                  { label: "After physical intervention", value: "post_pi" },
                  { label: "Casual observation", value: "casual" },
                  { label: "Medical appointment", value: "medical" },
                  { label: "Other", value: "other" },
                ],
                field_order: 4,
                section_id: "sec-bm-details",
              },
            ],
          },
          {
            id: "sec-bm-marks",
            title: "Mark / Injury Description",
            section_order: 2,
            fields: [
              {
                id: "f-bm-location",
                field_key: "body_location",
                field_type: "multi_select",
                label: "Location on body",
                required: true,
                options: [
                  { label: "Head", value: "head" },
                  { label: "Face", value: "face" },
                  { label: "Neck", value: "neck" },
                  { label: "Left shoulder / upper arm", value: "left_upper_arm" },
                  { label: "Right shoulder / upper arm", value: "right_upper_arm" },
                  { label: "Left forearm / wrist", value: "left_forearm" },
                  { label: "Right forearm / wrist", value: "right_forearm" },
                  { label: "Left hand", value: "left_hand" },
                  { label: "Right hand", value: "right_hand" },
                  { label: "Chest / sternum", value: "chest" },
                  { label: "Back (upper)", value: "back_upper" },
                  { label: "Back (lower)", value: "back_lower" },
                  { label: "Abdomen", value: "abdomen" },
                  { label: "Left hip / thigh", value: "left_thigh" },
                  { label: "Right hip / thigh", value: "right_thigh" },
                  { label: "Left knee / lower leg", value: "left_lower_leg" },
                  { label: "Right knee / lower leg", value: "right_lower_leg" },
                  { label: "Left foot / ankle", value: "left_foot" },
                  { label: "Right foot / ankle", value: "right_foot" },
                ],
                field_order: 1,
                section_id: "sec-bm-marks",
              },
              {
                id: "f-bm-type",
                field_key: "mark_type",
                field_type: "multi_select",
                label: "Type of mark / injury",
                required: true,
                options: [
                  { label: "Bruising", value: "bruising" },
                  { label: "Scratch / abrasion", value: "scratch" },
                  { label: "Cut / laceration", value: "cut" },
                  { label: "Burn / scald", value: "burn" },
                  { label: "Swelling", value: "swelling" },
                  { label: "Redness / rash", value: "redness" },
                  { label: "Self-harm mark", value: "self_harm" },
                  { label: "Bite mark", value: "bite" },
                  { label: "Other", value: "other" },
                ],
                field_order: 2,
                section_id: "sec-bm-marks",
              },
              {
                id: "f-bm-size",
                field_key: "approximate_size",
                field_type: "short_text",
                label: "Approximate size (e.g. 2cm × 1cm)",
                required: false,
                field_order: 3,
                section_id: "sec-bm-marks",
              },
              {
                id: "f-bm-colour",
                field_key: "colour_appearance",
                field_type: "short_text",
                label: "Colour / appearance (e.g. red, purple, yellow-green)",
                required: false,
                field_order: 4,
                section_id: "sec-bm-marks",
              },
              {
                id: "f-bm-description",
                field_key: "full_description",
                field_type: "long_text",
                label: "Full description of the mark / injury",
                required: true,
                field_order: 5,
                section_id: "sec-bm-marks",
              },
              {
                id: "f-bm-photo",
                field_key: "photo_evidence",
                field_type: "file_upload",
                label: "Photograph (if consented and appropriate)",
                required: false,
                field_order: 6,
                section_id: "sec-bm-marks",
              },
            ],
          },
          {
            id: "sec-bm-explanation",
            title: "Explanation & Response",
            section_order: 3,
            fields: [
              {
                id: "f-bm-explanation-given",
                field_key: "explanation_offered",
                field_type: "yes_no",
                label: "Did the young person offer an explanation?",
                required: true,
                field_order: 1,
                section_id: "sec-bm-explanation",
              },
              {
                id: "f-bm-explanation-detail",
                field_key: "explanation_detail",
                field_type: "long_text",
                label: "Young person's explanation (in their words where possible)",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "explanation_offered", operator: "equals", value: true },
                  },
                ],
                field_order: 2,
                section_id: "sec-bm-explanation",
              },
              {
                id: "f-bm-consistent",
                field_key: "explanation_consistent",
                field_type: "single_select",
                label: "Is the explanation consistent with the mark/injury?",
                required: false,
                options: [
                  { label: "Yes — consistent", value: "consistent" },
                  { label: "Partially consistent", value: "partial" },
                  { label: "No — inconsistent", value: "inconsistent" },
                  { label: "Unable to determine", value: "unknown" },
                ],
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "explanation_offered", operator: "equals", value: true },
                  },
                ],
                field_order: 3,
                section_id: "sec-bm-explanation",
              },
              {
                id: "f-bm-safeguarding-concern",
                field_key: "safeguarding_concern",
                field_type: "yes_no",
                label: "Does this raise a safeguarding concern?",
                required: true,
                field_order: 4,
                section_id: "sec-bm-explanation",
              },
              {
                id: "f-bm-manager-informed",
                field_key: "manager_informed",
                field_type: "yes_no",
                label: "Has the manager been informed?",
                required: true,
                field_order: 5,
                section_id: "sec-bm-explanation",
              },
              {
                id: "f-bm-action",
                field_key: "action_taken",
                field_type: "long_text",
                label: "Action taken as a result of this observation",
                required: true,
                field_order: 6,
                section_id: "sec-bm-explanation",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 4. Personal Education Plan (PEP) ────────────────────────────────────────
  personal_education_plan: {
    id: "tpl-pep",
    code: "personal_education_plan",
    name: "Personal Education Plan (PEP)",
    category: "Education",
    status: "approved",
    description: "Statutory Personal Education Plan for a looked after child",
    latest_version: {
      id: "v-pep-1",
      template_id: "tpl-pep",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-pep-overview",
            title: "PEP Overview",
            section_order: 1,
            fields: [
              {
                id: "f-pep-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-pep-overview",
              },
              {
                id: "f-pep-date",
                field_key: "pep_date",
                field_type: "date",
                label: "Date of PEP",
                required: true,
                field_order: 2,
                section_id: "sec-pep-overview",
              },
              {
                id: "f-pep-type",
                field_key: "pep_type",
                field_type: "single_select",
                label: "Type of PEP",
                required: true,
                options: [
                  { label: "Initial PEP (within 10 days of LAC status)", value: "initial" },
                  { label: "Review PEP", value: "review" },
                  { label: "Annual PEP", value: "annual" },
                  { label: "Transition PEP", value: "transition" },
                ],
                field_order: 3,
                section_id: "sec-pep-overview",
              },
              {
                id: "f-pep-school",
                field_key: "current_school",
                field_type: "short_text",
                label: "Current school / college / provision",
                required: true,
                field_order: 4,
                section_id: "sec-pep-overview",
              },
              {
                id: "f-pep-year",
                field_key: "year_group",
                field_type: "short_text",
                label: "Year group",
                required: true,
                field_order: 5,
                section_id: "sec-pep-overview",
              },
              {
                id: "f-pep-attendees",
                field_key: "attendees",
                field_type: "long_text",
                label: "Those present at the PEP meeting",
                required: true,
                help_text: "Include name and role of each attendee.",
                field_order: 6,
                section_id: "sec-pep-overview",
              },
            ],
          },
          {
            id: "sec-pep-attendance",
            title: "Attendance & Engagement",
            section_order: 2,
            fields: [
              {
                id: "f-pep-attendance-pct",
                field_key: "attendance_percentage",
                field_type: "number",
                label: "Current attendance percentage",
                required: true,
                field_order: 1,
                section_id: "sec-pep-attendance",
              },
              {
                id: "f-pep-punctuality",
                field_key: "punctuality",
                field_type: "single_select",
                label: "Punctuality",
                required: true,
                options: [
                  { label: "Good (rarely late)", value: "good" },
                  { label: "Some concerns", value: "some_concerns" },
                  { label: "Significant concern", value: "significant" },
                ],
                field_order: 2,
                section_id: "sec-pep-attendance",
              },
              {
                id: "f-pep-engagement",
                field_key: "engagement_school",
                field_type: "single_select",
                label: "Engagement with school / learning",
                required: true,
                options: [
                  { label: "Positive engagement", value: "positive" },
                  { label: "Variable — some challenges", value: "variable" },
                  { label: "Struggling to engage", value: "struggling" },
                  { label: "Currently not engaging", value: "not_engaging" },
                ],
                field_order: 3,
                section_id: "sec-pep-attendance",
              },
              {
                id: "f-pep-barriers",
                field_key: "barriers_to_learning",
                field_type: "long_text",
                label: "Barriers to learning (if any)",
                required: false,
                field_order: 4,
                section_id: "sec-pep-attendance",
              },
            ],
          },
          {
            id: "sec-pep-achievement",
            title: "Achievement & Progress",
            section_order: 3,
            fields: [
              {
                id: "f-pep-progress",
                field_key: "academic_progress",
                field_type: "long_text",
                label: "Academic progress since last PEP",
                required: true,
                help_text: "Include attainment levels, progress made in key subjects.",
                field_order: 1,
                section_id: "sec-pep-achievement",
              },
              {
                id: "f-pep-strengths",
                field_key: "strengths_interests",
                field_type: "long_text",
                label: "Strengths, interests and talents",
                required: false,
                field_order: 2,
                section_id: "sec-pep-achievement",
              },
              {
                id: "f-pep-pupil-premium",
                field_key: "pupil_premium_used",
                field_type: "long_text",
                label: "How has pupil premium / virtual school funding been used?",
                required: false,
                field_order: 3,
                section_id: "sec-pep-achievement",
              },
            ],
          },
          {
            id: "sec-pep-voice",
            title: "Child's Voice",
            section_order: 4,
            fields: [
              {
                id: "f-pep-child-view",
                field_key: "child_view_school",
                field_type: "live_voice_transcript",
                label: "What does the young person like/dislike about school?",
                help_text: "Record this in the young person's own words wherever possible.",
                required: false,
                field_order: 1,
                section_id: "sec-pep-voice",
              },
              {
                id: "f-pep-aspirations",
                field_key: "aspirations",
                field_type: "long_text",
                label: "Young person's aspirations and future goals",
                required: false,
                field_order: 2,
                section_id: "sec-pep-voice",
              },
            ],
          },
          {
            id: "sec-pep-targets",
            title: "SMART Targets",
            section_order: 5,
            fields: [
              {
                id: "f-pep-targets",
                field_key: "smart_targets",
                field_type: "long_text",
                label: "SMART targets for the next period (who, what, by when)",
                required: true,
                field_order: 1,
                section_id: "sec-pep-targets",
              },
              {
                id: "f-pep-review-date",
                field_key: "review_date",
                field_type: "date",
                label: "Date of next PEP review",
                required: true,
                field_order: 2,
                section_id: "sec-pep-targets",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 5. Child in Care Review Preparation ─────────────────────────────────────
  lac_review_prep: {
    id: "tpl-lac-review-prep",
    code: "lac_review_prep",
    name: "Child in Care Review — Residential Home Contribution",
    category: "Care Planning",
    status: "approved",
    description: "Home's contribution to a Looked After Child / Child in Care statutory review",
    latest_version: {
      id: "v-lac-review-prep-1",
      template_id: "tpl-lac-review-prep",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-lac-details",
            title: "Review Details",
            section_order: 1,
            fields: [
              {
                id: "f-lac-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-lac-details",
              },
              {
                id: "f-lac-review-date",
                field_key: "review_date",
                field_type: "date",
                label: "Date of Review",
                required: true,
                field_order: 2,
                section_id: "sec-lac-details",
              },
              {
                id: "f-lac-review-number",
                field_key: "review_number",
                field_type: "single_select",
                label: "Review number",
                required: true,
                options: [
                  { label: "Initial CiC Review (28 days)", value: "initial" },
                  { label: "Second review (3 months)", value: "second" },
                  { label: "Subsequent review", value: "subsequent" },
                ],
                field_order: 3,
                section_id: "sec-lac-details",
              },
              {
                id: "f-lac-completed-by",
                field_key: "completed_by",
                field_type: "staff_selector",
                label: "Contribution completed by",
                required: true,
                field_order: 4,
                section_id: "sec-lac-details",
              },
            ],
          },
          {
            id: "sec-lac-wellbeing",
            title: "Wellbeing & Daily Life",
            section_order: 2,
            fields: [
              {
                id: "f-lac-settling",
                field_key: "settling_in",
                field_type: "ai_assisted_narrative",
                label: "How is the young person settled in the home?",
                required: true,
                field_order: 1,
                section_id: "sec-lac-wellbeing",
              },
              {
                id: "f-lac-relationships",
                field_key: "peer_relationships",
                field_type: "long_text",
                label: "Relationships with peers in the home",
                required: true,
                field_order: 2,
                section_id: "sec-lac-wellbeing",
              },
              {
                id: "f-lac-staff-relationships",
                field_key: "staff_relationships",
                field_type: "long_text",
                label: "Relationships with staff",
                required: true,
                field_order: 3,
                section_id: "sec-lac-wellbeing",
              },
              {
                id: "f-lac-health",
                field_key: "physical_health",
                field_type: "long_text",
                label: "Physical health — appointments, concerns, progress",
                required: false,
                field_order: 4,
                section_id: "sec-lac-wellbeing",
              },
              {
                id: "f-lac-mental-health",
                field_key: "emotional_wellbeing",
                field_type: "long_text",
                label: "Emotional wellbeing and mental health",
                required: true,
                field_order: 5,
                section_id: "sec-lac-wellbeing",
              },
            ],
          },
          {
            id: "sec-lac-education",
            title: "Education & Activities",
            section_order: 3,
            fields: [
              {
                id: "f-lac-education",
                field_key: "education_update",
                field_type: "long_text",
                label: "Education — attendance, engagement, progress",
                required: true,
                field_order: 1,
                section_id: "sec-lac-education",
              },
              {
                id: "f-lac-activities",
                field_key: "activities_hobbies",
                field_type: "long_text",
                label: "Activities, hobbies, and positive interests",
                required: false,
                field_order: 2,
                section_id: "sec-lac-education",
              },
            ],
          },
          {
            id: "sec-lac-contact",
            title: "Family Contact",
            section_order: 4,
            fields: [
              {
                id: "f-lac-contact",
                field_key: "family_contact_summary",
                field_type: "long_text",
                label: "Summary of family / significant person contact",
                required: false,
                field_order: 1,
                section_id: "sec-lac-contact",
              },
              {
                id: "f-lac-contact-concerns",
                field_key: "contact_concerns",
                field_type: "yes_no",
                label: "Any concerns arising from contact?",
                required: true,
                field_order: 2,
                section_id: "sec-lac-contact",
              },
              {
                id: "f-lac-contact-concern-detail",
                field_key: "contact_concern_detail",
                field_type: "long_text",
                label: "Detail of concerns",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "contact_concerns", operator: "equals", value: true },
                  },
                ],
                field_order: 3,
                section_id: "sec-lac-contact",
              },
            ],
          },
          {
            id: "sec-lac-child-voice",
            title: "Child's Views",
            section_order: 5,
            fields: [
              {
                id: "f-lac-child-views",
                field_key: "child_views",
                field_type: "live_voice_transcript",
                label: "Young person's views on their placement and care",
                help_text: "Record in the young person's own words wherever possible.",
                required: false,
                field_order: 1,
                section_id: "sec-lac-child-voice",
              },
              {
                id: "f-lac-child-wishes",
                field_key: "child_wishes",
                field_type: "long_text",
                label: "Young person's wishes and feelings going forward",
                required: false,
                field_order: 2,
                section_id: "sec-lac-child-voice",
              },
            ],
          },
          {
            id: "sec-lac-recommendations",
            title: "Recommendations",
            section_order: 6,
            fields: [
              {
                id: "f-lac-recommendations",
                field_key: "recommendations",
                field_type: "long_text",
                label: "Home's recommendations for the review",
                required: true,
                field_order: 1,
                section_id: "sec-lac-recommendations",
              },
              {
                id: "f-lac-care-plan-changes",
                field_key: "care_plan_changes_needed",
                field_type: "yes_no",
                label: "Are any changes to the care plan recommended?",
                required: true,
                field_order: 2,
                section_id: "sec-lac-recommendations",
              },
              {
                id: "f-lac-care-plan-change-detail",
                field_key: "care_plan_change_detail",
                field_type: "long_text",
                label: "Detail of recommended changes",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "care_plan_changes_needed", operator: "equals", value: true },
                  },
                ],
                field_order: 3,
                section_id: "sec-lac-recommendations",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 6. Reg 44 Independent Person Visit ──────────────────────────────────────
  reg44_visit: {
    id: "tpl-reg44-visit",
    code: "reg44_visit",
    name: "Regulation 44 — Independent Person Visit Report",
    category: "Compliance",
    status: "approved",
    description: "Monthly independent person visit report (Reg 44, Children's Homes Regulations 2015)",
    latest_version: {
      id: "v-reg44-visit-1",
      template_id: "tpl-reg44-visit",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-r44-details",
            title: "Visit Details",
            section_order: 1,
            fields: [
              {
                id: "f-r44-home",
                field_key: "home_name",
                field_type: "short_text",
                label: "Home name",
                required: true,
                field_order: 1,
                section_id: "sec-r44-details",
              },
              {
                id: "f-r44-date",
                field_key: "visit_date",
                field_type: "date",
                label: "Date of visit",
                required: true,
                field_order: 2,
                section_id: "sec-r44-details",
              },
              {
                id: "f-r44-visitor",
                field_key: "independent_visitor_name",
                field_type: "short_text",
                label: "Independent person name",
                required: true,
                field_order: 3,
                section_id: "sec-r44-details",
              },
              {
                id: "f-r44-type",
                field_key: "visit_type",
                field_type: "single_select",
                label: "Type of visit",
                required: true,
                options: [
                  { label: "Announced", value: "announced" },
                  { label: "Unannounced", value: "unannounced" },
                ],
                field_order: 4,
                section_id: "sec-r44-details",
              },
              {
                id: "f-r44-manager-present",
                field_key: "registered_manager_present",
                field_type: "yes_no",
                label: "Was the registered manager present during the visit?",
                required: true,
                field_order: 5,
                section_id: "sec-r44-details",
              },
            ],
          },
          {
            id: "sec-r44-spoke-with",
            title: "People Spoken With",
            section_order: 2,
            fields: [
              {
                id: "f-r44-staff-spoken",
                field_key: "staff_spoken_with",
                field_type: "long_text",
                label: "Staff spoken with (names/roles, without identifying sensitive info)",
                required: true,
                field_order: 1,
                section_id: "sec-r44-spoke-with",
              },
              {
                id: "f-r44-yp-spoken",
                field_key: "young_people_spoken_with",
                field_type: "long_text",
                label: "Young people spoken with (initials/first names only)",
                required: false,
                field_order: 2,
                section_id: "sec-r44-spoke-with",
              },
            ],
          },
          {
            id: "sec-r44-statutory",
            title: "Statutory Requirements Review",
            section_order: 3,
            fields: [
              {
                id: "f-r44-reg-compliance",
                field_key: "regulations_met",
                field_type: "yes_no",
                label: "Is the home meeting the requirements of the Children's Homes Regulations 2015?",
                required: true,
                field_order: 1,
                section_id: "sec-r44-statutory",
              },
              {
                id: "f-r44-qos-standards",
                field_key: "qos_standards_met",
                field_type: "yes_no",
                label: "Is the home meeting the Quality of Care Standards?",
                required: true,
                field_order: 2,
                section_id: "sec-r44-statutory",
              },
              {
                id: "f-r44-welfare",
                field_key: "children_welfare_promoted",
                field_type: "yes_no",
                label: "Is the welfare of the children actively promoted?",
                required: true,
                field_order: 3,
                section_id: "sec-r44-statutory",
              },
            ],
          },
          {
            id: "sec-r44-observations",
            title: "Observations",
            section_order: 4,
            fields: [
              {
                id: "f-r44-strengths",
                field_key: "strengths_observed",
                field_type: "ai_assisted_narrative",
                label: "Strengths observed during the visit",
                required: true,
                field_order: 1,
                section_id: "sec-r44-observations",
              },
              {
                id: "f-r44-concerns",
                field_key: "concerns_observed",
                field_type: "long_text",
                label: "Concerns or areas for improvement",
                required: false,
                field_order: 2,
                section_id: "sec-r44-observations",
              },
              {
                id: "f-r44-safeguarding",
                field_key: "safeguarding_concerns",
                field_type: "yes_no",
                label: "Were any safeguarding concerns identified?",
                required: true,
                field_order: 3,
                section_id: "sec-r44-observations",
              },
              {
                id: "f-r44-safeguarding-detail",
                field_key: "safeguarding_detail",
                field_type: "long_text",
                label: "Detail of safeguarding concerns and actions taken",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "safeguarding_concerns", operator: "equals", value: true },
                  },
                ],
                field_order: 4,
                section_id: "sec-r44-observations",
              },
            ],
          },
          {
            id: "sec-r44-recommendations",
            title: "Recommendations",
            section_order: 5,
            fields: [
              {
                id: "f-r44-recommendations",
                field_key: "recommendations",
                field_type: "long_text",
                label: "Recommendations to the registered person / provider",
                required: true,
                field_order: 1,
                section_id: "sec-r44-recommendations",
              },
              {
                id: "f-r44-next-visit",
                field_key: "next_visit_date",
                field_type: "date",
                label: "Proposed date of next visit",
                required: false,
                field_order: 2,
                section_id: "sec-r44-recommendations",
              },
              {
                id: "f-r44-signature",
                field_key: "visitor_signature",
                field_type: "signature",
                label: "Independent person signature",
                required: true,
                field_order: 3,
                section_id: "sec-r44-recommendations",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 7. Transition Planning ───────────────────────────────────────────────────
  transition_plan: {
    id: "tpl-transition-plan",
    code: "transition_plan",
    name: "Transition Planning",
    category: "Care Planning",
    status: "approved",
    description: "Planning record for a young person's planned transition (move in, move on, or step-down)",
    latest_version: {
      id: "v-transition-plan-1",
      template_id: "tpl-transition-plan",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-tr-overview",
            title: "Transition Overview",
            section_order: 1,
            fields: [
              {
                id: "f-tr-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-tr-overview",
              },
              {
                id: "f-tr-type",
                field_key: "transition_type",
                field_type: "single_select",
                label: "Type of transition",
                required: true,
                options: [
                  { label: "Moving in to this home", value: "move_in" },
                  { label: "Moving to another residential placement", value: "move_on_residential" },
                  { label: "Moving to foster care", value: "move_on_foster" },
                  { label: "Supported living / independence", value: "independence" },
                  { label: "Returning home to family", value: "return_home" },
                  { label: "Emergency move (unplanned)", value: "emergency" },
                ],
                field_order: 2,
                section_id: "sec-tr-overview",
              },
              {
                id: "f-tr-planned-date",
                field_key: "planned_date",
                field_type: "date",
                label: "Planned date of transition",
                required: false,
                field_order: 3,
                section_id: "sec-tr-overview",
              },
              {
                id: "f-tr-completed-by",
                field_key: "completed_by",
                field_type: "staff_selector",
                label: "Plan completed by",
                required: true,
                field_order: 4,
                section_id: "sec-tr-overview",
              },
            ],
          },
          {
            id: "sec-tr-preparation",
            title: "Preparation",
            section_order: 2,
            fields: [
              {
                id: "f-tr-yp-view",
                field_key: "yp_views_transition",
                field_type: "live_voice_transcript",
                label: "Young person's views on the transition",
                help_text: "Record the young person's views in their own words where possible.",
                required: false,
                field_order: 1,
                section_id: "sec-tr-preparation",
              },
              {
                id: "f-tr-yp-anxieties",
                field_key: "yp_anxieties",
                field_type: "long_text",
                label: "Young person's anxieties and worries about the transition",
                required: false,
                field_order: 2,
                section_id: "sec-tr-preparation",
              },
              {
                id: "f-tr-preparation-steps",
                field_key: "preparation_steps",
                field_type: "long_text",
                label: "Steps being taken to prepare the young person for the transition",
                required: true,
                field_order: 3,
                section_id: "sec-tr-preparation",
              },
              {
                id: "f-tr-visits-planned",
                field_key: "visits_planned",
                field_type: "long_text",
                label: "Planned introductory visits / activities (if applicable)",
                required: false,
                field_order: 4,
                section_id: "sec-tr-preparation",
              },
            ],
          },
          {
            id: "sec-tr-information",
            title: "Information to Transfer",
            section_order: 3,
            fields: [
              {
                id: "f-tr-documents",
                field_key: "documents_to_transfer",
                field_type: "multi_select",
                label: "Documents to be transferred",
                required: true,
                options: [
                  { label: "Care plan", value: "care_plan" },
                  { label: "Risk assessment", value: "risk_assessment" },
                  { label: "Behaviour support plan", value: "behaviour_support" },
                  { label: "Medical records summary", value: "medical" },
                  { label: "Education records / PEP", value: "education" },
                  { label: "Life story work", value: "life_story" },
                  { label: "Missing from care protocols", value: "mfc_protocol" },
                  { label: "Medication chart", value: "medication" },
                  { label: "Incident records (summary)", value: "incidents" },
                ],
                field_order: 1,
                section_id: "sec-tr-information",
              },
              {
                id: "f-tr-key-info",
                field_key: "key_information_summary",
                field_type: "ai_assisted_narrative",
                label: "Key information summary for the receiving placement / team",
                help_text: "Summarise what the young person and any new carers/workers need to know to ensure continuity of care.",
                required: true,
                field_order: 2,
                section_id: "sec-tr-information",
              },
              {
                id: "f-tr-risks",
                field_key: "transition_risks",
                field_type: "long_text",
                label: "Known risks during the transition period",
                required: false,
                field_order: 3,
                section_id: "sec-tr-information",
              },
            ],
          },
          {
            id: "sec-tr-after",
            title: "After the Transition",
            section_order: 4,
            fields: [
              {
                id: "f-tr-contact-plan",
                field_key: "post_transition_contact",
                field_type: "long_text",
                label: "Plan for staying in contact / any ongoing support",
                required: false,
                field_order: 1,
                section_id: "sec-tr-after",
              },
              {
                id: "f-tr-review-date",
                field_key: "transition_review_date",
                field_type: "date",
                label: "Date for review of transition plan",
                required: false,
                field_order: 2,
                section_id: "sec-tr-after",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 8. Complaints & Compliments Record ──────────────────────────────────────
  complaints_compliments: {
    id: "tpl-complaints",
    code: "complaints_compliments",
    name: "Complaints & Compliments Record",
    category: "Compliance",
    status: "approved",
    description: "Record of a complaint, concern or compliment received about the home",
    latest_version: {
      id: "v-complaints-1",
      template_id: "tpl-complaints",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-cc-details",
            title: "Record Details",
            section_order: 1,
            fields: [
              {
                id: "f-cc-type",
                field_key: "record_type",
                field_type: "single_select",
                label: "Type",
                required: true,
                options: [
                  { label: "Complaint", value: "complaint" },
                  { label: "Compliment", value: "compliment" },
                  { label: "Concern (informal)", value: "concern" },
                  { label: "Formal complaint (escalated)", value: "formal_complaint" },
                ],
                field_order: 1,
                section_id: "sec-cc-details",
              },
              {
                id: "f-cc-date-received",
                field_key: "date_received",
                field_type: "date",
                label: "Date received",
                required: true,
                field_order: 2,
                section_id: "sec-cc-details",
              },
              {
                id: "f-cc-received-by",
                field_key: "received_by",
                field_type: "staff_selector",
                label: "Received by",
                required: true,
                field_order: 3,
                section_id: "sec-cc-details",
              },
              {
                id: "f-cc-from",
                field_key: "from_whom",
                field_type: "single_select",
                label: "Received from",
                required: true,
                options: [
                  { label: "Young person", value: "young_person" },
                  { label: "Parent / guardian", value: "parent" },
                  { label: "Social worker", value: "social_worker" },
                  { label: "Staff member", value: "staff" },
                  { label: "Independent visitor", value: "independent_visitor" },
                  { label: "Ofsted / regulator", value: "ofsted" },
                  { label: "Other professional", value: "other_professional" },
                  { label: "Anonymous", value: "anonymous" },
                ],
                field_order: 4,
                section_id: "sec-cc-details",
              },
              {
                id: "f-cc-method",
                field_key: "method_received",
                field_type: "single_select",
                label: "Method received",
                required: true,
                options: [
                  { label: "In person", value: "in_person" },
                  { label: "Telephone", value: "telephone" },
                  { label: "Email", value: "email" },
                  { label: "Letter", value: "letter" },
                  { label: "Via Ofsted", value: "ofsted" },
                  { label: "Other", value: "other" },
                ],
                field_order: 5,
                section_id: "sec-cc-details",
              },
            ],
          },
          {
            id: "sec-cc-content",
            title: "Content",
            section_order: 2,
            fields: [
              {
                id: "f-cc-summary",
                field_key: "summary",
                field_type: "ai_assisted_narrative",
                label: "Summary of the complaint / compliment / concern",
                required: true,
                field_order: 1,
                section_id: "sec-cc-content",
              },
              {
                id: "f-cc-child-involved",
                field_key: "relates_to_child",
                field_type: "yes_no",
                label: "Does this relate to a specific young person?",
                required: true,
                field_order: 2,
                section_id: "sec-cc-content",
              },
              {
                id: "f-cc-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young person (if applicable)",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "relates_to_child", operator: "equals", value: true },
                  },
                ],
                field_order: 3,
                section_id: "sec-cc-content",
              },
            ],
          },
          {
            id: "sec-cc-response",
            title: "Response & Outcome",
            section_order: 3,
            fields: [
              {
                id: "f-cc-acknowledged-date",
                field_key: "acknowledged_date",
                field_type: "date",
                label: "Date acknowledged",
                required: false,
                field_order: 1,
                section_id: "sec-cc-response",
              },
              {
                id: "f-cc-response-narrative",
                field_key: "response_narrative",
                field_type: "long_text",
                label: "Response provided / actions taken",
                required: false,
                field_order: 2,
                section_id: "sec-cc-response",
              },
              {
                id: "f-cc-outcome",
                field_key: "outcome",
                field_type: "single_select",
                label: "Outcome",
                required: false,
                options: [
                  { label: "Resolved — upheld", value: "resolved_upheld" },
                  { label: "Resolved — not upheld", value: "resolved_not_upheld" },
                  { label: "Resolved — partially upheld", value: "resolved_partial" },
                  { label: "Escalated to provider", value: "escalated" },
                  { label: "Referred to Ofsted", value: "referred_ofsted" },
                  { label: "Ongoing", value: "ongoing" },
                  { label: "N/A (compliment)", value: "compliment" },
                ],
                field_order: 3,
                section_id: "sec-cc-response",
              },
              {
                id: "f-cc-learning",
                field_key: "learning_identified",
                field_type: "long_text",
                label: "Learning identified from this record",
                required: false,
                field_order: 4,
                section_id: "sec-cc-response",
              },
              {
                id: "f-cc-resolved-date",
                field_key: "resolved_date",
                field_type: "date",
                label: "Date resolved (if applicable)",
                required: false,
                field_order: 5,
                section_id: "sec-cc-response",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 9. Night Check Record ────────────────────────────────────────────────────
  night_check_record: {
    id: "tpl-night-check",
    code: "night_check_record",
    name: "Night Check / Welfare Check Record",
    category: "Daily Care",
    status: "approved",
    description: "Record of overnight welfare checks for young people in the home",
    latest_version: {
      id: "v-night-check-1",
      template_id: "tpl-night-check",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-nc-shift",
            title: "Shift Details",
            section_order: 1,
            fields: [
              {
                id: "f-nc-date",
                field_key: "check_date",
                field_type: "date",
                label: "Date (night of)",
                required: true,
                field_order: 1,
                section_id: "sec-nc-shift",
              },
              {
                id: "f-nc-staff",
                field_key: "staff_on_duty",
                field_type: "staff_selector",
                label: "Staff on duty (sleep-in / waking night)",
                required: true,
                field_order: 2,
                section_id: "sec-nc-shift",
              },
              {
                id: "f-nc-shift-type",
                field_key: "shift_type",
                field_type: "single_select",
                label: "Shift type",
                required: true,
                options: [
                  { label: "Sleep-in", value: "sleep_in" },
                  { label: "Waking night", value: "waking_night" },
                ],
                field_order: 3,
                section_id: "sec-nc-shift",
              },
            ],
          },
          {
            id: "sec-nc-checks",
            title: "Welfare Checks",
            section_order: 2,
            fields: [
              {
                id: "f-nc-check-22",
                field_key: "check_2200",
                field_type: "single_select",
                label: "22:00 — Young people present and settled?",
                required: true,
                options: [
                  { label: "All present and settled", value: "all_present" },
                  { label: "All present, some unsettled", value: "some_unsettled" },
                  { label: "One or more absent", value: "absent" },
                  { label: "N/A (not applicable at this time)", value: "na" },
                ],
                field_order: 1,
                section_id: "sec-nc-checks",
              },
              {
                id: "f-nc-check-00",
                field_key: "check_0000",
                field_type: "single_select",
                label: "00:00 — Young people present and settled?",
                required: true,
                options: [
                  { label: "All present and settled", value: "all_present" },
                  { label: "All present, some unsettled", value: "some_unsettled" },
                  { label: "One or more absent", value: "absent" },
                  { label: "N/A (not applicable at this time)", value: "na" },
                ],
                field_order: 2,
                section_id: "sec-nc-checks",
              },
              {
                id: "f-nc-check-02",
                field_key: "check_0200",
                field_type: "single_select",
                label: "02:00 — Young people present and settled?",
                required: true,
                options: [
                  { label: "All present and settled", value: "all_present" },
                  { label: "All present, some unsettled", value: "some_unsettled" },
                  { label: "One or more absent", value: "absent" },
                  { label: "N/A (not applicable at this time)", value: "na" },
                ],
                field_order: 3,
                section_id: "sec-nc-checks",
              },
              {
                id: "f-nc-check-04",
                field_key: "check_0400",
                field_type: "single_select",
                label: "04:00 — Young people present and settled?",
                required: true,
                options: [
                  { label: "All present and settled", value: "all_present" },
                  { label: "All present, some unsettled", value: "some_unsettled" },
                  { label: "One or more absent", value: "absent" },
                  { label: "N/A (not applicable at this time)", value: "na" },
                ],
                field_order: 4,
                section_id: "sec-nc-checks",
              },
              {
                id: "f-nc-check-06",
                field_key: "check_0600",
                field_type: "single_select",
                label: "06:00 — Young people present and settled?",
                required: true,
                options: [
                  { label: "All present and settled", value: "all_present" },
                  { label: "All present, some unsettled", value: "some_unsettled" },
                  { label: "One or more absent", value: "absent" },
                  { label: "N/A (not applicable at this time)", value: "na" },
                ],
                field_order: 5,
                section_id: "sec-nc-checks",
              },
            ],
          },
          {
            id: "sec-nc-incidents",
            title: "Incidents & Notes",
            section_order: 3,
            fields: [
              {
                id: "f-nc-incidents",
                field_key: "incidents_during_night",
                field_type: "yes_no",
                label: "Any incidents or concerns during the night?",
                required: true,
                field_order: 1,
                section_id: "sec-nc-incidents",
              },
              {
                id: "f-nc-incident-detail",
                field_key: "incident_detail",
                field_type: "long_text",
                label: "Detail of incidents / concerns",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "incidents_during_night", operator: "equals", value: true },
                  },
                ],
                field_order: 2,
                section_id: "sec-nc-incidents",
              },
              {
                id: "f-nc-notes",
                field_key: "overnight_notes",
                field_type: "long_text",
                label: "General overnight notes / handover to day shift",
                required: false,
                field_order: 3,
                section_id: "sec-nc-incidents",
              },
              {
                id: "f-nc-medication",
                field_key: "medication_given",
                field_type: "yes_no",
                label: "Was any medication given overnight?",
                required: true,
                field_order: 4,
                section_id: "sec-nc-incidents",
              },
              {
                id: "f-nc-medication-detail",
                field_key: "medication_detail",
                field_type: "long_text",
                label: "Medication detail (what, who, when, dose)",
                required: false,
                conditional_rules: [
                  {
                    type: "show",
                    when: { fieldKey: "medication_given", operator: "equals", value: true },
                  },
                ],
                field_order: 5,
                section_id: "sec-nc-incidents",
              },
              {
                id: "f-nc-signature",
                field_key: "staff_signature",
                field_type: "signature",
                label: "Staff signature",
                required: true,
                field_order: 6,
                section_id: "sec-nc-incidents",
              },
            ],
          },
        ],
      },
    },
  },

  // ── 10. De-escalation / Positive Behaviour Support Plan ─────────────────────
  deescalation_plan: {
    id: "tpl-deescalation-plan",
    code: "deescalation_plan",
    name: "De-escalation & Positive Behaviour Support Plan",
    category: "Care Planning",
    status: "approved",
    description: "Individual plan for supporting a young person through periods of distress — practical strategies to prevent and de-escalate",
    latest_version: {
      id: "v-deescalation-plan-1",
      template_id: "tpl-deescalation-plan",
      version_number: 1,
      is_published: true,
      created_at: new Date().toISOString(),
      schema: {
        sections: [
          {
            id: "sec-de-overview",
            title: "Overview",
            section_order: 1,
            fields: [
              {
                id: "f-de-child",
                field_key: "child_id",
                field_type: "young_person_selector",
                label: "Young Person",
                required: true,
                field_order: 1,
                section_id: "sec-de-overview",
              },
              {
                id: "f-de-date",
                field_key: "plan_date",
                field_type: "date",
                label: "Plan date",
                required: true,
                field_order: 2,
                section_id: "sec-de-overview",
              },
              {
                id: "f-de-completed-by",
                field_key: "completed_by",
                field_type: "staff_selector",
                label: "Plan completed by",
                required: true,
                field_order: 3,
                section_id: "sec-de-overview",
              },
              {
                id: "f-de-agreed-with-yp",
                field_key: "agreed_with_yp",
                field_type: "yes_no",
                label: "Has this plan been agreed with the young person?",
                required: true,
                field_order: 4,
                section_id: "sec-de-overview",
              },
              {
                id: "f-de-review-date",
                field_key: "review_date",
                field_type: "date",
                label: "Date for plan review",
                required: false,
                field_order: 5,
                section_id: "sec-de-overview",
              },
            ],
          },
          {
            id: "sec-de-understanding",
            title: "Understanding the Young Person",
            section_order: 2,
            fields: [
              {
                id: "f-de-triggers",
                field_key: "known_triggers",
                field_type: "long_text",
                label: "Known triggers (what tends to cause distress or escalation?)",
                required: true,
                field_order: 1,
                section_id: "sec-de-understanding",
              },
              {
                id: "f-de-early-signs",
                field_key: "early_warning_signs",
                field_type: "long_text",
                label: "Early warning signs (what do you notice when they are beginning to struggle?)",
                required: true,
                field_order: 2,
                section_id: "sec-de-understanding",
              },
              {
                id: "f-de-escalation-signs",
                field_key: "escalation_signs",
                field_type: "long_text",
                label: "Escalation signs (signs the situation is becoming more serious)",
                required: true,
                field_order: 3,
                section_id: "sec-de-understanding",
              },
              {
                id: "f-de-yp-perspective",
                field_key: "yp_own_words",
                field_type: "live_voice_transcript",
                label: "Young person's own description of what helps when they are distressed",
                help_text: "Use the young person's own words wherever possible.",
                required: false,
                field_order: 4,
                section_id: "sec-de-understanding",
              },
            ],
          },
          {
            id: "sec-de-strategies",
            title: "De-escalation Strategies",
            section_order: 3,
            fields: [
              {
                id: "f-de-primary",
                field_key: "primary_strategies",
                field_type: "ai_assisted_narrative",
                label: "Primary de-escalation strategies (what works for this young person)",
                help_text: "Be specific — name the approaches, language, activities or sensory tools that help.",
                required: true,
                field_order: 1,
                section_id: "sec-de-strategies",
              },
              {
                id: "f-de-things-to-avoid",
                field_key: "things_to_avoid",
                field_type: "long_text",
                label: "Things to avoid (what makes things worse?)",
                required: true,
                field_order: 2,
                section_id: "sec-de-strategies",
              },
              {
                id: "f-de-language",
                field_key: "helpful_language",
                field_type: "long_text",
                label: "Helpful language and phrases",
                required: false,
                field_order: 3,
                section_id: "sec-de-strategies",
              },
              {
                id: "f-de-environment",
                field_key: "environmental_adjustments",
                field_type: "long_text",
                label: "Environmental adjustments (space, noise, lighting, etc.)",
                required: false,
                field_order: 4,
                section_id: "sec-de-strategies",
              },
              {
                id: "f-de-trusted-person",
                field_key: "preferred_staff",
                field_type: "staff_selector",
                label: "Preferred / trusted staff member to involve when escalating",
                required: false,
                field_order: 5,
                section_id: "sec-de-strategies",
              },
            ],
          },
          {
            id: "sec-de-post",
            title: "Post-Incident Recovery",
            section_order: 4,
            fields: [
              {
                id: "f-de-recovery",
                field_key: "recovery_strategies",
                field_type: "long_text",
                label: "Recovery strategies — how to support the young person after an incident",
                required: true,
                field_order: 1,
                section_id: "sec-de-post",
              },
              {
                id: "f-de-repair",
                field_key: "repair_approach",
                field_type: "long_text",
                label: "Relational repair — how do you rebuild connection after a difficult episode?",
                required: false,
                field_order: 2,
                section_id: "sec-de-post",
              },
            ],
          },
        ],
      },
    },
  },
};

export const PHASE4_TEMPLATE_LIST = Object.values(PHASE4_TEMPLATES);
